/**
 * This file is generated by scripts/generate-unions.mjs. Do not edit it.
 *
 * Each alias is the union of the variants the spec lists in that schema’s
 * `discriminator.mapping` (or its `oneOf`), so `switch` on the discriminator
 * narrows and editors complete the variant’s own fields.
 */
import type { components } from './openapi.js';

/**
 * List of buttons of a card.
 * Discriminated on `type`. Union of 3 variants.
 */
export type MessagesApiCarouselTemplateButtonUnion =
  | components['schemas']['MessagesApiCarouselTemplateQuickReplyButton']
  | components['schemas']['MessagesApiCarouselTemplateOpenUrlButton']
  | components['schemas']['MessagesApiCarouselTemplatePhoneNumberButton'];

/**
 * Incoming messages
 * Discriminated on `event`. Union of 3 variants.
 */
export type MessagesApiInboundEventUnion =
  | components['schemas']['MessagesApiMoEvent']
  | components['schemas']['MessagesApiInboundTypingStartedEvent']
  | components['schemas']['MessagesApiInboundTypingStoppedEvent'];

/**
 * Body of the message.
 * Discriminated on `type`. Union of 18 variants.
 */
export type MessagesApiMessageBodyUnion =
  | components['schemas']['MessagesApiMessageTextBody']
  | components['schemas']['MessagesApiMessageImageBody']
  | components['schemas']['MessagesApiMessageVideoBody']
  | components['schemas']['MessagesApiMessageDocumentBody']
  | components['schemas']['MessagesApiMessageRichLinkBody']
  | components['schemas']['MessagesApiMessageAuthenticationRequestBody']
  | components['schemas']['MessagesApiMessageListBody']
  | components['schemas']['MessagesApiMessageCarouselBody']
  | components['schemas']['MessagesApiMessageLocationBody']
  | components['schemas']['MessagesApiMessageContactBody']
  | components['schemas']['MessagesApiMessageStickerBody']
  | components['schemas']['MessagesApiMessageProductBody']
  | components['schemas']['MessagesApiMessageMixedBody']
  | components['schemas']['MessagesApiMessageFlowBody']
  | components['schemas']['MessagesApiMessageTimePickerBody']
  | components['schemas']['MessagesApiMessageOrderRequestBody']
  | components['schemas']['MessagesApiMessageOrderStatusBody']
  | components['schemas']['MessagesApiMessageFormBody'];

/**
 * List of buttons of the message.
 * Discriminated on `type`. Union of 6 variants.
 */
export type MessagesApiMessageButtonUnion =
  | components['schemas']['MessagesApiMessageReplyButton']
  | components['schemas']['MessagesApiMessageOpenUrlButton']
  | components['schemas']['MessagesApiMessageDialPhoneButton']
  | components['schemas']['MessagesApiMessageShowLocationButton']
  | components['schemas']['MessagesApiMessageRequestLocationButton']
  | components['schemas']['MessagesApiMessageAddCalendarEventButton'];

/**
 * Action of the flow.
 * Discriminated on `type`. Union of 2 variants.
 */
export type MessagesApiMessageFlowActionUnion =
  | components['schemas']['MessagesApiMessageFlowNavigateAction']
  | components['schemas']['MessagesApiMessageFlowDataExchangeAction'];

/**
 * An array of different pages to be shown in the form. If INTRO page is included it will always appear first.
 * Discriminated on `type`. Union of 5 variants.
 */
export type MessagesApiMessageFormPageUnion =
  | components['schemas']['MessagesApiMessageSelectFormPage']
  | components['schemas']['MessagesApiMessagePickerFormPage']
  | components['schemas']['MessagesApiMessageDatePickerFormPage']
  | components['schemas']['MessagesApiMessageInputFormPage']
  | components['schemas']['MessagesApiMessageIntroFormPage'];

/**
 * Header of the message.
 * Discriminated on `type`. Union of 1 variant.
 */
export type MessagesApiMessageHeaderUnion =
  | components['schemas']['MessagesApiMessageTextHeader'];

/**
 * Required for WhatsApp, optional for Apple. Type of the payment.
 * Discriminated on `type`. Union of 9 variants.
 */
export type MessagesApiMessagePaymentConfigurationUnion =
  | components['schemas']['MessagesApiMessagePgPayuPaymentConfiguration']
  | components['schemas']['MessagesApiMessageUpiPgRazorpayPaymentConfiguration']
  | components['schemas']['MessagesApiMessageUpiPayuPaymentConfiguration']
  | components['schemas']['MessagesApiMessageBrazilPaymentConfiguration']
  | components['schemas']['MessagesApiMessageBrazilPixDcPaymentConfiguration']
  | components['schemas']['MessagesApiMessageBrazilLinkPaymentConfiguration']
  | components['schemas']['MessagesApiMessageBrazilBoletoPaymentConfiguration']
  | components['schemas']['MessagesApiMessageUpiIntentPaymentConfiguration']
  | components['schemas']['MessagesApiMessageApplePayPaymentConfiguration'];

/**
 * Content of the message.
 * Discriminated on `type`. Union of 16 variants.
 */
export type MessagesApiMoEventContentUnion =
  | components['schemas']['MessagesApiMoEventTextContent']
  | components['schemas']['MessagesApiMoEventSubjectContent']
  | components['schemas']['MessagesApiMoEventImageContent']
  | components['schemas']['MessagesApiMoEventAudioContent']
  | components['schemas']['MessagesApiMoEventVideoContent']
  | components['schemas']['MessagesApiMoEventDocumentContent']
  | components['schemas']['MessagesApiMoEventFileContent']
  | components['schemas']['MessagesApiMoEventUrlContent']
  | components['schemas']['MessagesApiMoEventButtonReplyContent']
  | components['schemas']['MessagesApiMoEventListReplyContent']
  | components['schemas']['MessagesApiMoEventLocationContent']
  | components['schemas']['MessagesApiMoEventAuthenticationResponseContent']
  | components['schemas']['MessagesApiMoEventFlowResponseContent']
  | components['schemas']['MessagesApiMoEventPaymentResponseContent']
  | components['schemas']['MessagesApiMoEventFormContent']
  | components['schemas']['MessagesApiMoEventReactionContent'];

/**
 * Array of event objects of a single event or multiple events sent
 * Discriminated on `event`. Union of 3 variants.
 */
export type MessagesApiOutboundEventUnion =
  | components['schemas']['MessagesApiOutboundTypingStartedEvent']
  | components['schemas']['MessagesApiOutboundTypingStoppedEvent']
  | components['schemas']['MessagesApiOutboundSeenEvent'];

/**
 * Body of a template message.
 * Discriminated on `type`. Union of 2 variants.
 */
export type MessagesApiTemplateBodyUnion =
  | components['schemas']['MessagesApiTemplateTextBody']
  | components['schemas']['MessagesApiTemplateCarouselBody'];

/**
 * List of buttons of a template message.
 * Discriminated on `type`. Union of 7 variants.
 */
export type MessagesApiTemplateButtonUnion =
  | components['schemas']['MessagesApiTemplateQuickReplyButton']
  | components['schemas']['MessagesApiTemplateOpenUrlButton']
  | components['schemas']['MessagesApiTemplatePhoneNumberButton']
  | components['schemas']['MessagesApiTemplateFlowButton']
  | components['schemas']['MessagesApiTemplateCopyCodeButton']
  | components['schemas']['MessagesApiTemplateCatalogButton']
  | components['schemas']['MessagesApiTemplateMultiProductButton'];

/**
 * Header of a card.
 * Discriminated on `type`. Union of 2 variants.
 */
export type MessagesApiTemplateCarouselCardHeaderUnion =
  | components['schemas']['MessagesApiTemplateCarouselCardImageHeader']
  | components['schemas']['MessagesApiTemplateCarouselCardVideoHeader'];

/**
 * Header of a template message.
 * Discriminated on `type`. Union of 5 variants.
 */
export type MessagesApiTemplateHeaderUnion =
  | components['schemas']['MessagesApiTemplateTextHeader']
  | components['schemas']['MessagesApiTemplateDocumentHeader']
  | components['schemas']['MessagesApiTemplateImageHeader']
  | components['schemas']['MessagesApiTemplateVideoHeader']
  | components['schemas']['MessagesApiTemplateLocationHeader'];

/**
 * Format of the payment.
 * Discriminated on `type`. Union of 1 variant.
 */
export type MessagesApiUpiIntentPaymentFormatUnion =
  | components['schemas']['MessagesApiUpiIntentPaymentLinkFormat'];

/**
 * Array of destination objects for where messages are being sent. A valid destination is required. **`Channels Destination` is required when sending messages with defined failover.**
 * Union of the schemas this `oneOf` allows.
 */
export type MessageDestinationUnion =
  | components['schemas']['MessagesApiChannelsDestination']
  | components['schemas']['MessagesApiToDestination'];

/**
 * Provides options for configuring a message failover. When message fails it will be sent over channels in order specified in an array. It has to contain unique entries per channel and it cannot contain
 * Union of the schemas this `oneOf` allows.
 */
export type MessagesApiBaseFailoverUnion =
  | components['schemas']['MessagesApiFailover']
  | components['schemas']['MessagesApiTemplateFailover'];

/**
 * Array of message objects of a single message or multiple messages sent under one bulk ID.
 * Union of the schemas this `oneOf` allows.
 */
export type MessagesApiBaseMessageUnion =
  | components['schemas']['MessagesApiMessage']
  | components['schemas']['MessagesApiTemplateMessage'];

/**
 * Mixed items.
 * Union of the schemas this `oneOf` allows.
 */
export type MessagesApiMessageMixedItemUnion =
  | components['schemas']['MessagesApiMessageMixedMediaItem']
  | components['schemas']['MessagesApiMessageMixedTextItem'];
