#!/usr/bin/env node
/**
 * Emit discriminated-union aliases for the polymorphic schemas.
 *
 * `openapi-typescript` renders each concrete variant with a narrowed literal
 * discriminator (`type: "TEXT"`), but it leaves the *base* schema as the open
 * parent — `MessagesApiMessageBody` generates as `{ type: MessageBodyType }`,
 * which narrows to nothing and completes to nothing. The union has to be the
 * union of the variants, and the spec already states exactly that in each
 * schema's `discriminator.mapping` and in each `oneOf`.
 *
 * So: derive them. Hand-writing eighteen body variants and fifteen more unions
 * would drift the first time Infobip adds a content type; this file reads the
 * mapping and fails CI's spec-drift check instead.
 *
 * Usage: node scripts/generate-unions.mjs <normalized-spec.json> <output.ts>
 */
import { readFile, writeFile } from 'node:fs/promises';

const [, , specPath, outputPath] = process.argv;
if (!specPath || !outputPath) {
  console.error('usage: node scripts/generate-unions.mjs <spec.json> <output.ts>');
  process.exit(2);
}

const document = JSON.parse(await readFile(specPath, 'utf8'));
const schemas = document.components?.schemas ?? {};

/** `#/components/schemas/Foo` and bare `Foo` both name a schema. */
const schemaName = (ref) => ref.replace(/^#\/components\/schemas\//, '');

const discriminated = [];
const plain = [];

for (const [name, schema] of Object.entries(schemas)) {
  const mapping = schema.discriminator?.mapping;
  if (mapping && Object.keys(mapping).length > 0) {
    const variants = [...new Set(Object.values(mapping).map(schemaName))];
    const missing = variants.filter((variant) => !(variant in schemas));
    if (missing.length > 0) {
      console.error(
        `${name}: discriminator maps to ${missing.join(', ')}, which the document does not define.`,
      );
      process.exit(1);
    }
    discriminated.push({
      name,
      property: schema.discriminator.propertyName,
      variants,
      description: schema.description,
    });
    continue;
  }
  if (Array.isArray(schema.oneOf) && schema.oneOf.every((entry) => entry.$ref)) {
    plain.push({
      name,
      variants: schema.oneOf.map((entry) => schemaName(entry.$ref)),
      description: schema.description,
    });
  }
}

discriminated.sort((a, b) => a.name.localeCompare(b.name));
plain.sort((a, b) => a.name.localeCompare(b.name));

const lines = [
  '/**',
  ' * This file is generated by scripts/generate-unions.mjs. Do not edit it.',
  ' *',
  ' * Each alias is the union of the variants the spec lists in that schema’s',
  ' * `discriminator.mapping` (or its `oneOf`), so `switch` on the discriminator',
  ' * narrows and editors complete the variant’s own fields.',
  ' */',
  "import type { components } from './openapi.js';",
  '',
];

const suffix = 'Union';
for (const { name, property, variants, description } of discriminated) {
  lines.push('/**');
  if (description) lines.push(` * ${oneLine(description)}`);
  lines.push(
    ` * Discriminated on \`${property}\`. Union of ${variants.length} variant${
      variants.length === 1 ? '' : 's'
    }.`,
  );
  lines.push(' */');
  lines.push(`export type ${name}${suffix} =`);
  for (const variant of variants) lines.push(`  | components['schemas']['${variant}']`);
  lines[lines.length - 1] += ';';
  lines.push('');
}

for (const { name, variants, description } of plain) {
  lines.push('/**');
  if (description) lines.push(` * ${oneLine(description)}`);
  lines.push(' * Union of the schemas this `oneOf` allows.');
  lines.push(' */');
  lines.push(`export type ${name}${suffix} =`);
  for (const variant of variants) lines.push(`  | components['schemas']['${variant}']`);
  lines[lines.length - 1] += ';';
  lines.push('');
}

await writeFile(outputPath, `${lines.join('\n')}`, 'utf8');
console.log(
  `generated ${discriminated.length} discriminated + ${plain.length} oneOf unions → ${outputPath}`,
);

/** Collapse a spec description to a single JSDoc line. */
function oneLine(text) {
  return text.replace(/\s+/g, ' ').replace(/\*\//g, '*\\/').trim().slice(0, 200);
}
